// generated by qs-build. do not edit.

package web

import (
	"encoding/json"
	"errors"

	"github.com/QuestScreen/api/web/config"
	"github.com/QuestScreen/api/web/server"
)

// LoadConfig loads configuration values of this module.
func LoadConfig(ctx server.Context, input []byte) (map[string]config.Controller, error) {
	var items map[string]json.RawMessage
	if err := json.Unmarshal(input, items); err != nil {
		return nil, err
	}
	ret := make(map[string]config.Controller)
	for key := range items {
		return nil, errors.New("unknown field: " + key)
	}
	return ret, nil
}
