package web

// Code generated by qs-build. DO NOT EDIT.

import (
	background "github.com/QuestScreen/QuestScreen/plugins/base/web/background"
	herolist "github.com/QuestScreen/QuestScreen/plugins/base/web/herolist"
	overlays "github.com/QuestScreen/QuestScreen/plugins/base/web/overlays"
	title "github.com/QuestScreen/QuestScreen/plugins/base/web/title"
	"github.com/QuestScreen/QuestScreen/web"
)

func RegisterModules(reg web.PluginRegistrator) error {
	if err := reg.RegisterModule("background", background.NewState, background.ConfigDescriptor); err != nil {
		return err
	}
	if err := reg.RegisterModule("herolist", herolist.NewState, herolist.ConfigDescriptor); err != nil {
		return err
	}
	if err := reg.RegisterModule("overlays", overlays.NewState, overlays.ConfigDescriptor); err != nil {
		return err
	}
	if err := reg.RegisterModule("title", title.NewState, title.ConfigDescriptor); err != nil {
		return err
	}
	return nil
}
