// generated by qs-build. do not edit.
package web

import (
	background "github.com/QuestScreen/QuestScreen/plugins/base/web/background"
	herolist "github.com/QuestScreen/QuestScreen/plugins/base/web/herolist"
	overlays "github.com/QuestScreen/QuestScreen/plugins/base/web/overlays"
	title "github.com/QuestScreen/QuestScreen/plugins/base/web/title"
	"github.com/QuestScreen/api/web"
)

func RegisterModules(reg web.PluginRegistrator) error {
	if err := reg.RegisterModule("background", background.NewState); err != nil {
		return err
	}
	if err := reg.RegisterModule("herolist", herolist.NewState); err != nil {
		return err
	}
	if err := reg.RegisterModule("overlays", overlays.NewState); err != nil {
		return err
	}
	if err := reg.RegisterModule("title", title.NewState); err != nil {
		return err
	}
	return nil
}
