// generated by qs-build. do not edit.

package web

import (
	"encoding/json"
	"errors"

	p1 "github.com/QuestScreen/QuestScreen/plugins/base/title"
	p2 "github.com/QuestScreen/QuestScreen/plugins/base/title"
	"github.com/QuestScreen/api/web/config"
	"github.com/QuestScreen/api/web/server"
)

// LoadConfig loads configuration values of this module.
func LoadConfig(ctx server.Context, input []byte) (map[string]config.Controller, error) {
	var items map[string]json.RawMessage
	if err := json.Unmarshal(input, items); err != nil {
		return nil, err
	}
	ret := make(map[string]config.Controller)
	{
		raw, ok := items["Font"]
		if !ok {
			return nil, errors.New("field missing: " + "Font")
		}
		var value p1.Controller
		if err := json.Unmarshal(raw, value); err != nil {
			return nil, errors.New("in config item Font: " + err.Error())
		}
		ret["Font"] = value
		delete(items, "Font")
	}
	{
		raw, ok := items["Background"]
		if !ok {
			return nil, errors.New("field missing: " + "Background")
		}
		var value p2.Controller
		if err := json.Unmarshal(raw, value); err != nil {
			return nil, errors.New("in config item Background: " + err.Error())
		}
		ret["Background"] = value
		delete(items, "Background")
	}
	for key := range items {
		return nil, errors.New("unknown field: " + key)
	}
	return ret, nil
}
