{renderImports, imap0, ...}: plugins: with builtins; ''package main

// Code generated by nix. DO NOT EDIT.

import (
	"github.com/QuestScreen/QuestScreen/web"
	${renderImports "web/" plugins}
)

func registerPlugins(loader *pluginLoader) error {
	${let
		indexedPlugins = imap0 (index: p: {inherit index; plugin = p;}) plugins;
		loadModule = module: ''if err := loader.RegisterModule(${toJSON module.name}, ${module.importName}.NewState, web.ConfigDescriptor${module.importName});
		err != nil {
		return err
	}'';
		loadPlugin = {index, plugin}: ''
	loader.id = ${toJSON plugin.id}
	loader.index = ${toString index}
	${concatStringsSep "\n\t" (map loadModule plugin.modules)};
	'';
	in concatStringsSep "\n\t" (map loadPlugin indexedPlugins)
	}
	return nil
}
''