package api

import (
	"time"

	"github.com/veandco/go-sdl2/sdl"
	"gopkg.in/yaml.v3"
)

// the interface declared in this file are to be implemented by
// a pnpscreen module.

// ResourceCollectionIndex indexes all resource collections of a module.
type ResourceCollectionIndex int

// ModuleIndex identifies the module internally.
type ModuleIndex int

// ModuleState describes the state of a module. It is written to and loaded
// from a group's state.yaml.
//
// All funcs are expected to be called in the server thread.
type ModuleState interface {
	SerializableItem
	// HandleAction handles an action requested via the web interface.
	//
	// The first return value will be serialized to JSON and sent back via the web
	// interface.
	//
	// The second return value will be handed over to the module's InitTransition
	// which will be called in the OpenGL thread after HandleAction has returned.
	// For thread safety, that value should be constructed from scratch and not be
	// a pointer into the ModuleState object.
	//
	// If an error is returned, InitTransition will not be called and both return
	// values will be ignored.
	HandleAction(index int, payload []byte) (interface{}, interface{}, error)
	// CreateModuleData generates a data object that contains all required data
	// for the module to rebuild its state. The returned data object will be
	// handed over to the module's RebuildState. For thread safety, it should not
	// be a pointer into the ModuleState object.
	CreateModuleData() interface{}
}

// ResourceSelector defines a subdirectory and a filename suffix list.
// Those will be used to collect resource files for this module in the
// data directories.
type ResourceSelector struct {
	// may be empty, in which case resource files are searched directly
	// in the module directories.
	Subdirectory string
	// filters files by suffix. If empty or nil, no filter will be applied
	// (note however that files starting with a dot will always be filtered out).
	Suffixes []string
}

// ModuleDescriptor describes a module.
type ModuleDescriptor struct {
	// Name is the human-readable name of the module.
	Name string
	// ID is a unique string, used for identifying the module inside
	// HTTP URLs and in the filesystem. Therefore, the ID is restricted to ASCII
	// letters, digits, and the symbols `.,-_`
	// Note that internally, a module is identified by the ModuleIndex given
	// to CreateModule.
	ID string
	// ResourceCollections lists selectors for resource collections of this
	// module. The maximum ResourceCollectionIndex available to this module is
	// len(ResourceCollections()) - 1.
	ResourceCollections []ResourceSelector
	// Actions() is the list of actions callable via HTTP POST that should be
	// registered for this module.
	Actions []string
	// DefaultConfig returns a configuration object with default values.
	// This must be a pointer to a struct in which each field is a pointer to an
	// item implementing ConfigItem.
	// All fields of the struct object must hold a non-nil value.
	DefaultConfig interface{}
	// CreateModule creates the module object. This will only be called once
	// during app initialization, making the module a singleton object.
	//
	// The index argument should be retained by the module for identifying itself
	// to the environment.
	CreateModule func(renderer *sdl.Renderer, env StaticEnvironment) (Module, error)
	// CreateState will be called in the server thread. It shall create a
	// ModuleState for the module created by CreateModule.
	//
	// input will reflect the Persisted layout of the serialized state as
	// generated by the state's SerializableView method.
	// It may be nil in which case the state will be created with default values.
	//
	// Communication between ModuleState and Module will be done via the state's
	// HandleAction and CreateModuleData methods which create data, and the
	// module's InitTransition and RebuildState methods which consume that data.
	CreateState func(input *yaml.Node, env Environment, index ModuleIndex) (ModuleState, error)
}

// RenderContext is the context given to all rendering funcs of a module
type RenderContext struct {
	Env      Environment
	Renderer *sdl.Renderer
}

// Module describes a module object. This object belongs with the OpenGL thread.
// All funcs are called in the OpenGL thread unless noted otherwise.
type Module interface {
	// Descriptor shall return the ModuleDescriptor that has created this module.
	Descriptor() *ModuleDescriptor
	// SetConfig sets the module's calculated configuration. The given config
	// object will be of the type specified by ModuleDescriptor.ConfigType().
	// The config object will have all fields set to non-nil values.
	// The rendering thread will always call RebuildState after SetConfig.
	SetConfig(config interface{})
	// InitTransition will be called after the current ModuleState has been
	// modified via HandleAction.
	// data contains the data generated by HandleAction.
	//
	// The return value is the duration of the transition initiated by this call.
	// For that duration, the render thread will continuously call
	// TransitionStep and Render. After the time has passed,
	// FinishTransition and Render will be called to render the final state.
	//
	// if 0 is returned, TransitionStep will never be called; if a negative
	// value is returned, neither FinishTransition nor Render will be
	// called.
	InitTransition(ctx RenderContext, data interface{}) time.Duration
	// TransitionStep should update the renderer's current state while
	// transitioning. A call to TransitionStep() will always immediately be
	// followed by a call to Render().
	//
	// The given elapsed time is guaranteed to always be smaller than what was
	// returned by InitTransition().
	TransitionStep(ctx RenderContext, elapsed time.Duration)
	// FinishTransition() is for cleanup after a transition and for preparing the
	// final state. It will be called exactly once for each call to
	// InitTransition() that returned a non-negative value.
	//
	// A call to FinishTransition() will always immediately be followed by a call
	// to Render().
	FinishTransition(ctx RenderContext)
	// Render renders the Module.s current state.
	Render(ctx RenderContext)
	// RebuildState will be called after any action that requires rebuilding the
	// Module's state, such as a scene, config or group change. For scene and
	// group change, data contains data generated by the ModuleState's
	// CreateModuleData; it will be nil for config changes.
	//
	// A call to RebuildState will always immediately be followed by a call to
	// Render.
	RebuildState(ctx RenderContext, data interface{})
}
