{mapAttrsToList, injectWeb, ...}: plugins: configTypes: with builtins; ''
package web

// Code generated by nix. DO NOT EDIT.

import (
	"github.com/QuestScreen/api/web/modules"
	${concatStringsSep "\n\t" (mapAttrsToList (k: v: "${v} ${toJSON (injectWeb k)}") configTypes)}
)

${let
	configItemDescr = name: item: ''{
		Constructor: ${item.packageImportName}.New${item.type},
		Name: ${toJSON (item.label or name)},
	},'';
	moduleDescriptor = module: ''
var ConfigDescriptor${module.importName} = []modules.ConfigItem{
	${concatStringsSep "\n\t" (mapAttrsToList configItemDescr module.config)}
}'';
	pluginDescriptors = plugin:
		concatStringsSep "\n\n" (map moduleDescriptor plugin.modules);
in concatStringsSep "\n\n" (map pluginDescriptors plugins)}
''