package web

import (
	"github.com/QuestScreen/api/web/modules"
)

// PluginRegistrator is the interface given to a plugin to register modules to
// the web UI core. It is used from autogenerated code.
type PluginRegistrator interface {
	RegisterModule(id string, constructor modules.Constructor,
		configItems []modules.ConfigItem) error
}
